on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.1.0
        with:
          dry-run: false # Check out the console output before setting this to false
          exempt-branches-regex: ^(main|master)$
          days-before-branch-stale: 90
          days-before-branch-delete: 0
